vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
